### ISSUE TITLE
Searched Seeds Counter

### ISSUE THREAD

**Issue by Dextrome** [Cr4xy/noita-seed-tool#15]
I don't quite understand how the SEARCHED SEEDS counter works, it seems to be a lot higher than actual seeds searched? 

The found seed numbers that match the search criteria always go up in numerical order. 
So why is the searched seed counter at 200 million, while the next found seed number only goes up by 35 million for example? (went from seed 134,545,678 to seed 170,246,436 while the search seed counter was already over 200 million)

Is the counter just broken or am I misinterpreting something?

**Comment by Cr4xy** [comment]
Thanks for the report! This is indeed a bug.
The counting code is working fine for one thread, but for multiple cores the logic doesn't work. The value is basically off by some factor around the number of cores you have in your system.

**Comment by Dextrome** [comment]
nice, thanks for the fast fix :)
