### ISSUE TITLE
Perks not displaying properly on displays with width 769px-1279px

### ISSUE THREAD

**Issue by ThreeHats** [Cr4xy/noita-seed-tool#22]
The div that holds the perks is getting squished when displayed on screens with width equaling 769px through 1279px. Noticed this while using the site on my vertical display.

![Screenshot 2024-06-08 013836](https://github.com/Cr4xy/noita-seed-tool/assets/33038393/4587e4c2-ccad-405d-8c15-1fba513fb5b4)

**Comment by Cr4xy** [comment]
Closed via #23
