### ISSUE TITLE
[suggestion] continue search from last seed+1

### ISSUE THREAD

**Issue by ctcDNightmare** [Cr4xy/noita-seed-tool#4]
Just a small idea worth thinking about:

When you find a seed which looks okayish but you want to find another one further up the number-chain, you have to add -not filters etc to make it work but it would be awesome to just click search again with given startseed or have a "continue" button for that.

Just a thought that crossed my mind,
What do you think?

**Comment by Cr4xy** [comment]
Sorry for the late response - Thanks for the suggestion, I like your idea! I think it makes the UI a bit friendlier and is also very easy to implement. Will look into it soon™️ ;)
